const dataSourceTemp2 = [
	{
		key: "1",
		date: "04/15/2022",
		firstname: "Hayden",
		lastname: "Bramson",
		revenue: 29.99,
		type: "Caregiver",
		state: "AZ",
		organization: "Phoenex Children's Hospital",
		resource_title:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry",
		status: "Active",
		status2: "In Progress",
		priority: "High",
		user_type: "Caregiver",
		cert_of_completion: "03/11/22",
	},
	{
		key: "2",
		date: "04/11/2022",
		firstname: "Hayden",
		lastname: "Blake",
		revenue: 29.99,
		type: "Caregiver",
		state: "AZ",
		organization: "Banner",
		resource_title:
			"Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
		status: "Active",
		status2: "Not Started",
		priority: "Low",
		user_type: "Both",
		cert_of_completion: "02/15/22",
	},
	{
		key: "3",
		date: "03/23/2022",
		firstname: "Hayden",
		lastname: "Collinsworth",
		revenue: 59.99,
		type: "Provider",
		state: "AZ",
		organization: "N/A",
		resource_title:
			"It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged",
		status: "Draft",
		status2: "Completed",
		priority: "Medium",
		user_type: "Caregiver",
		cert_of_completion: "01/01/22",
	},
	{
		key: "4",
		date: "03/18/2022",
		firstname: "Hayden",
		lastname: "Jacobs",
		revenue: 59.99,
		type: "Provider",
		state: "CA",
		organization: "Cigna",
		resource_title:
			"It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages",
		status: "Active",
		status2: "Completed",
		priority: "High",
		user_type: "Careprovider",
		cert_of_completion: "11/11/21",
	},
	{
		key: "5",
		date: "03/01/2022",
		firstname: "Hayden",
		lastname: "Knorr",
		revenue: 29.99,
		type: "Caregiver",
		state: "AZ",
		organization: "Homewatch",
		resource_title:
			"desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
		status: "Draft",
		status2: "Completed",
		priority: "High",
		user_type: "Caregiver",
		cert_of_completion: "10/11/21",
	},
];

export default dataSourceTemp2;
