const optionSports = [
	{ value: "Badminton", label: "Badminton" },
	{ value: "Baseball (Boys)", label: "Baseball (Boys)" },
	{ value: "Basketball", label: "Basketball" },
	{ value: "Cheerleading", label: "Cheerleading" },
	{ value: "Cross Country", label: "Cross Country" },
	{ value: "Field Hockey", label: "Field Hockey" },
	{ value: "Flag Football (Girls)", label: "Flag Football (Girls)" },
	{ value: "Flag Football (Girls)", label: "Flag Football (Girls)" },
	{ value: "Football (Boys)", label: "Football (Boys)" },
	{ value: "Golf", label: "Golf" },
	{ value: "Gymnastics", label: "Gymnastics" },
	{ value: "Hockey", label: "Hockey" },
	{ value: "Lacrosse", label: "Lacrosse" },
	{ value: "Soccer", label: "Soccer" },
	{ value: "Softball (Girls)", label: "Softball (Girls)" },
	{ value: "Swimming &amp; Diving", label: "Swimming &amp; Diving" },
	{ value: "Tennis", label: "Tennis" },
	{ value: "Track &amp; Field", label: "Track &amp; Field" },
	{ value: "Volleyball", label: "Volleyball" },
	{ value: "Water Polo", label: "Water Polo" },
	{ value: "Weightlifting", label: "Weightlifting" },
	{ value: "Wrestling", label: "Wrestling" },
];

export default optionSports;
