const sampleUserData = {
	birthdate: null,
	created_at: "2022-07-18T13:20:42.000000Z",
	edit_permission: "No",
	email: "admin@test.com",
	email_verified_at: "2022-07-18 13:20:42",
	firstname: "John",
	gender: null,
	id: 1,
	lastname: "Admin",
	manager_id: null,
	managers_coverage_area: null,
	middlename: null,
	name_ext: null,
	nick_name: null,
	one_time_modal: 0,
	phone_number: null,
	profile_image: null,
	role: "Admin",
	status: "Active",
	stripe_customer_id: null,
	updated_at: "2022-07-18T13:20:42.000000Z",
	username: "admin",
};
export default sampleUserData;
