const tempUsers = [
	{
		account_type: "Athlete Guardian",
		billing_city: "buenavista",
		billing_country: "12",
		billing_state: "CT",
		billing_street_address: "ad",
		billing_street_address2: "asd",
		billing_zip: "123",
		card_expiry: "25/01",
		"confirm-password": "admin123",
		confirm_contact_number: 123456789,
		confirm_email: "athletepar@test.com",
		contact_number: 123456789,
		credit_card_name: "Parent Jongkak",
		credit_card_number: "4242 4424 4242 4242",
		cvv: "123",
		email: "athletepar@test.com",
		firstname: "Jong",
		guardian_confirm_email: "guardian@test.com",
		guardian_email: "guardian@test.com",
		guardian_firstname: "Parent Jong",
		guardian_lastname: "Guardian Kak",
		guardian_username: "guardian",
		is_over_16_years_old: "Yes",
		lastname: "Kak",
		password: "admin123",
		program_type: "Starter - $59.99",
		role: "Athlete Guardian",
		state: "AK",
		username: "athletepar",
	},
	{
		account_type: "Athlete",
		billing_city: "Purok 1, Agong-ong, Buenavista, Agusan Del Norte",
		billing_country: "248",
		billing_state: "CT",
		billing_street_address: "sadasd",
		billing_street_address2: "asd",
		billing_zip: "8601",
		card_expiry: "25/01",
		"confirm-password": "admi1n23",
		confirm_contact_number: 123456789,
		confirm_email: "athlete@test.com",
		contact_number: 123456789,
		credit_card_name: "athlete",
		credit_card_number: "4242 4242 4242 4242",
		cvv: "123",
		email: "athlete@test.com",
		firstname: "John",
		guardian_permission: "Yes",
		is_over_16_years_old: "No",
		lastname: "Kok",
		password: "admin123",
		program_type: "Starter - $59.99",
		role: "Athlete",
		state: "AZ",
		username: "athlete",
	},
	{
		account_type: "Coach",
		"confirm-password": "admin123",
		confirm_contact_number: 123456789,
		confirm_email: "coach@test.com",
		contact_number: 123456789,
		email: "coach@test.com",
		firstname: "Jean",
		lastname: "Coach",
		password: "admin123",
		role: "Coach",
		state: "CO",
		username: "coach",
	},
	{
		account_type: "Admin",
		"confirm-password": "admin123",
		confirm_contact_number: 123456789,
		confirm_email: "admin@test.com",
		contact_number: 123456789,
		email: "admin@test.com",
		firstname: "Jean",
		lastname: "Admin",
		password: "admin123",
		role: "Admin",
		state: "CO",
		username: "admin",
	},
	{
		account_type: "Manager",
		"confirm-password": "admin123",
		confirm_contact_number: 123456789,
		confirm_email: "manager@test.com",
		contact_number: 123456789,
		email: "manager@test.com",
		firstname: "Jean",
		lastname: "Manager",
		password: "admin123",
		role: "Manager",
		state: "CO",
		username: "manager",
	},
	{
		account_type: "Assessor",
		"confirm-password": "admin123",
		confirm_contact_number: 123456789,
		confirm_email: "assessor@test.com",
		contact_number: 123456789,
		email: "assessor@test.com",
		firstname: "Jean",
		lastname: "Assessor",
		password: "admin123",
		role: "Assessor",
		state: "CO",
		username: "assessor",
	},
];

export default tempUsers;
